#!/usr/bin/env bash

# Load icon mapping function
source "$HOME/.config/sketchybar/helpers/icon_map.sh"

# Some events send additional information specific to the event in the $INFO
# variable. E.g. the front_app_switched event sends the name of the newly
# focused application in the $INFO variable:
# https://felixkratz.github.io/SketchyBar/config/events#events-and-scripting
if [ "$SENDER" = "front_app_switched" ] && [ ! -z "$INFO" ]; then
  # Get the app icon using the mapping function
  __icon_map "$INFO"
  APP_ICON="$icon_result"
  
  sketchybar --set "$NAME" \
                   icon="$APP_ICON" \
                   label="$INFO"
fi
