#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonight"

create_workspace_bracket_for_monitor() {
  parameters=("$@")
  monitor_id=${parameters[0]}
  monitor_workspaces=("${parameters[@]:1}")
  
  if [ $monitor_id -eq 1 ]; then
    sketchybar --add item workspaces_spacer_center center \
               --set      workspaces_spacer_center \
                          width=4 \
                          background.drawing=off \
                          label.drawing=off
  fi
  
  for workspace_id in ${monitor_workspaces[@]}; do
    sketchybar --add item  workspaces."$monitor_id"."$workspace_id" center \
                          --subscribe workspaces."$monitor_id"."$workspace_id" aerospace_workspace_change \
                          --set       workspaces."$monitor_id"."$workspace_id" \
                                      background.drawing=off \
                                      click_script="aerospace workspace $workspace_id" \
                                      label="$workspace_id" \
                                      label.width="25" \
                                      script="$PLUGIN_DIR/aerospace $workspace_id"
  done
}

sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_service_mode_enabled_changed

monitor_ids=($(aerospace list-monitors | awk '{print $1}'))

for monitor_id in ${monitor_ids[@]}; do
  workspaces=($(aerospace list-workspaces --monitor $monitor_id --empty no))
  create_workspace_bracket_for_monitor $monitor_id ${workspaces[@]}
done
