#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonight"

# Define all workspaces from aerospace config
IFS=$'\n' WORKSPACES=($(aerospace list-workspaces --monitor all --empty no))

# Create workspace items
for workspace in "${WORKSPACES[@]}"; do
    sketchybar --add item "aerospace.$workspace" left \
               --set "aerospace.$workspace" \
                     icon="" \
                     icon.font="$ICON_BASE_FONT:Bold:13.0" \
                     icon.color="$white" \
                     icon.padding_left=6 \
                     icon.y_offset=0 \
                     icon.font_size=12 \
                     label="" \
                     label.padding_right=9 \
                     label.padding_left=8 \
                     label.y_offset=-1 \
                     background.drawing=off \
                     background.padding_right=10 \
                     background.height=23 \
                     background.corner_radius=50 \
                     script="$PLUGIN_DIR/aerospace.sh" \
                     click_script="aerospace workspace $workspace"

    sketchybar --subscribe "aerospace.$workspace" front_app_switched 
    sketchybar --subscribe "aerospace.$workspace" system_woke 
    sketchybar --subscribe "aerospace.$workspace" aerospace_workspace_change
done

sketchybar --add item "aerospace.focused" left \
           --set "aerospace.focused" \
                 background.drawing=off \
                 background.padding_right=10 \
                 background.height=23 \
                 background.corner_radius=23 \
                 script="$PLUGIN_DIR/aerospace_focused.sh"

sketchybar --subscribe "aerospace.focused" aerospace_workspace_change
