#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonight"

CAT_LABEL_COLOR="$red"

sketchybar --add item cat left \
           --set      cat \
                      icon="" \
                      icon.color="$magenta" \
                      icon.padding_left=6 \
                      icon.padding_right=6 \
                      background.drawing=off \
                      label.drawing=off
