#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonight"

FRONT_APP_LABEL_COLOR="$red"

sketchybar --add item front_app left \
           --subscribe front_app front_app_switched \
           --set       front_app \
                       background.drawing=off \
                       icon.font="$APP_ICON_FONT" \
                       icon.color="$FRONT_APP_LABEL_COLOR" \
                       icon.padding_left=8 \
                       icon.padding_right=8 \
                       label.color="$FRONT_APP_LABEL_COLOR" \
                       label.padding_left=0 \
                       label.padding_right=0 \
                       script="$PLUGIN_DIR/front_app"
