#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonight"

sketchybar --add item volume right \
           --set volume \
                 icon.font="$ICON_FONT" \
                 icon.color="$cyan" \
                 icon.padding_left=8 \
                 icon.padding_right=6 \
                 label.color="$cyan" \
                 label.padding_left=0 \
                 label.padding_right=8 \
                 background.drawing=off \
                 script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change
