#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonight"

sketchybar --add item weather right \
           --set weather \
                 icon.font="$ICON_FONT" \
                 icon.color="$magenta" \
                 icon.padding_left=8 \
                 icon.padding_right=4 \
                 label.color="$magenta" \
                 label.padding_left=0 \
                 label.padding_right=8 \
                 background.drawing=off \
                 update_freq=1800 \
                 script="$PLUGIN_DIR/weather.sh" \
           --subscribe weather system_woke
