os:
  editPreset: "nvim"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

customCommands:
  - key: "E"
    description: "Add empty commit"
    context: "commits"
    loadingText: "Committing empty commit..."
    command: 'git commit --allow-empty -m "{{.Form.Message}}"'
    prompts:
      - type: "input"
        key: "Message"
        title: "Empty commit message"

  - key: "C"
    command: "cz c"
    description: "Commit with commitizen"
    context: "files"