return {
	"jakewvincent/mkdnflow.nvim",
	ft = "markdown",
	opts = {
		modules = {
			bib = false,
			buffers = true,
			conceal = true,
			cursor = false,
			folds = false,
			links = true,
			lists = true,
			maps = true,
			paths = true,
			tables = false,
			yaml = false,
		},
		links = {
			style = "wiki",
			conceal = true,
		},
		to_do = {
			statuses = {
				not_started = { symbol = " " },
				complete = { symbol = "x" },
			},
			status_order = { "not_started", "complete" },
			status_propagation = {
				up = true,
			},
		},
		mappings = {
			MkdnEnter                  = { { "n", "v" }, "gf" },
			MkdnGoBack                 = false,
			MkdnNextLink               = { "n", "<Tab>" },
			MkdnPrevLink               = { "n", "<S-Tab>" },
			MkdnToggleToDo             = false,
			MkdnNewListItem            = { "n", "ml" },
			MkdnNewListItemBelowInsert = false,
			MkdnNewListItemAboveInsert = false,
			MkdnExtendList             = false,
			MkdnUpdateNumbering        = false,
			MkdnIncreaseHeading        = false,
			MkdnDecreaseHeading        = false,
			MkdnNextHeading            = false,
			MkdnPrevHeading            = false,
			MkdnCreateLink             = false,
			MkdnCreateLinkFromClipboard = false,
			MkdnFollowLink             = false,
			MkdnDestroyLink            = false,
			MkdnTagSpan                = false,
			MkdnMoveSource             = false,
			MkdnYankFileAnchorLink     = false,
			MkdnTableNextCell          = false,
			MkdnTablePrevCell          = false,
			MkdnTableNextRow           = false,
			MkdnTablePrevRow           = false,
			MkdnTableNewRowBelow       = false,
			MkdnTableNewRowAbove       = false,
			MkdnTableNewColAfter       = false,
			MkdnTableNewColBefore      = false,
			MkdnFoldSection            = false,
			MkdnUnfoldSection          = false,
			MkdnTab                    = false,
			MkdnSTab                   = false,
		},
	},
}
