# Options
set -g default-terminal "ghostty"
set -s extended-keys on # enable extended keys
set -as terminal-features "xterm*:extkeys"  # enable xterm keys
set -sg terminal-overrides ",*:RGB"  # true color support
set -g escape-time 10 # disable delays on escape sequences
set -g mouse on
set -g renumber-windows on  # keep numbering sequential
set -g repeat-time 700 
set -g base-index 1
set -g pane-base-index 1
set -g detach-on-destroy off 
# Theme: borders
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=#ff6b9d
# Theme: status
set -g status-style bg=default,fg=white,bright
set -g status-left ""
set -g status-right "#[fg=yellow,bright]#S"
# Theme: status (windows)
set -g window-status-format "●"
set -g window-status-current-format "●"
set -g window-status-current-style "fg=#{?window_zoomed_flag,yellow,#ff6b9d}"
set -g window-status-bell-style "fg=red,nobold"
# shell
set -g default-shell /bin/zsh
set -g default-command /bin/zsh
set -g allow-passthrough on
set -g set-clipboard on

# prefix
set -g prefix C-b
set -g prefix2 C-space

# reload
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

# split (with cwd preservation)
bind C-v split-window -h -c "#{pane_current_path}"
bind C-s split-window -v -c "#{pane_current_path}"

# bind -n + resize-pane -U 5
# bind -n _ resize-pane -D 5
# bind -n - resize-pane -L 5
# bind -n = resize-pane -R 5
#
# new window (with cwd preservation)
bind c new-window -c "#{pane_current_path}"
bind -r n next-window
bind -r v previous-window
bind -r p previous-window

bind -r C-o rotate-window

#ldefault split bindings with cwd preservation
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# panel
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# session
bind L switch-client -n
bind H switch-client -p
# vim mode selection
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# TMUX_FZF
TMUX_FZF_LAUNCH_KEY="C-f"

# Plugins
# set -g @plugin 'sainnhe/tmux-fzf'
# set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @vim_navigator_prefix_mapping_clear_screen ""
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-save 'P' # 사용하지 않는 키로 설정
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-boot 'on'
set -g @continuum-boot-options 'ghostty'
run '~/.tmux/plugins/tpm/tpm'


bind d display-popup -h 60 -w 200 -E "workmux dashboard"
bind b run-shell "workmux sidebar"
